prices:
  DIAMOND: 1500
  DIAMOND_ORE: 2500
  COBBLESTONE: 0.25
  IRON_ORE: 75
  IRON_INGOT: 125
  GOLD_ORE: 85
  GOLD_INGOT: 135
  COAL: 25
  COAL_ORE: 50
  REDSTONE: 15
  REDSTONE_ORE: 75
  EMERALD: 2000
  EMERALD_ORE: 10000
pickaxe:
  leveling:
    blocks: 500
    multiplier: 2
